---
title: "Variables"
format: docx
---

All definitions assume reverse scoring has already been done.

## Morals and Values

+------------------------------+--------------------+---------------+------------+-----------------------------+
| Variable Name                | Variable Label     | Variable Type | Source     | Definition                  |
+==============================+====================+===============+============+=============================+
| Individualism & Collectivism | indiv_collectivism | numeric       | ic_01:     | The mean of ic_01 : ic_15   |
|                              |                    |               |            |                             |
|                              |                    |               | ic_15      |                             |
+------------------------------+--------------------+---------------+------------+-----------------------------+
| Rebelliousness (complete)    | rebel_comp         | numeric       | reb_01:    | The mean of rb_01 : rb_09   |
|                              |                    |               |            |                             |
|                              |                    |               | reb_09     |                             |
+------------------------------+--------------------+---------------+------------+-----------------------------+
| Rebelliousness (trolling)    | rebel_troll        | numeric       | reb_01:    | The mean of rb_01 : rb_04   |
|                              |                    |               |            |                             |
|                              |                    |               | reb_04     |                             |
+------------------------------+--------------------+---------------+------------+-----------------------------+
| Rebelliousness               | rebel_act          | numeric       | reb_04:    | The mean of rb_05 : rb_09   |
|                              |                    |               |            |                             |
| (activism)                   |                    |               | reb_09     |                             |
+------------------------------+--------------------+---------------+------------+-----------------------------+
| Individual Choice Norms      | choice_norms       | numeric       | icn_01:    | The mean of icn_01 : icn_06 |
|                              |                    |               |            |                             |
|                              |                    |               | icn_06     |                             |
+------------------------------+--------------------+---------------+------------+-----------------------------+

## Cognitive Styles

+-----------------------------+-------------------+------------------+-----------+-----------------------------------------------------------+
| Variable Name               | Variable Label    | Variable Type    | Source    | Definition                                                |
|                             |                   |                  |           |                                                           |
|                             |                   |                  | (section) |                                                           |
+=============================+===================+==================+===========+===========================================================+
| Tolerance of Ambiguity      | ambiguity_tol     | numeric          | at_01:    | The mean of at_01: at_13                                  |
|                             |                   |                  |           |                                                           |
|                             |                   |                  | at_13     |                                                           |
+-----------------------------+-------------------+------------------+-----------+-----------------------------------------------------------+
| Cognitive Style (correct)   | crt_correct       | numeric/binomial | crt_01:   | The mean (proportion) of crt_01: crt_07 that are correct  |
|                             |                   |                  |           |                                                           |
|                             |                   |                  | crt_07    |                                                           |
+-----------------------------+-------------------+------------------+-----------+-----------------------------------------------------------+
| Cognitive Style             | crt_type          | numeric/binomial | crt_01:   | The mean (proportion) of crt_01:crt_07 that are intuitive |
|                             |                   |                  |           |                                                           |
| (intuitive)                 |                   |                  | crt_07    |                                                           |
+-----------------------------+-------------------+------------------+-----------+-----------------------------------------------------------+
| Non-Verbal Reasoning        | nverb_reason      | numeric          |           |                                                           |
+-----------------------------+-------------------+------------------+-----------+-----------------------------------------------------------+
| Moralisation of Rationality | rationality_moral | numeric          | mor_01:   | $$ \frac{1}{13} \sum_{i=01}^{13} at_{i} $$                |
|                             |                   |                  |           |                                                           |
|                             |                   |                  | mor_09    | The mean of at_01: at_13                                  |
+-----------------------------+-------------------+------------------+-----------+-----------------------------------------------------------+
| Importance of Rationality   | rationality_imp   | numeric          | imp_01:   | The mean of imp_01 : imp_06                               |
|                             |                   |                  |           |                                                           |
|                             |                   |                  | imp_06    |                                                           |
+-----------------------------+-------------------+------------------+-----------+-----------------------------------------------------------+

## Socialisation

+-----------------------------+----------------+------------------+-----------+--------------------------------------------+
| Variable Name               | Variable Label | Variable Type    | Source    | Definition                                 |
|                             |                |                  |           |                                            |
|                             |                |                  | (section) |                                            |
+=============================+================+==================+===========+============================================+
| CREDs                       | cred_exposure  | numeric          | sd_01:    | The mean of at_01: at_13                   |
|                             |                |                  |           |                                            |
|                             |                |                  | sd_08     |                                            |
+-----------------------------+----------------+------------------+-----------+--------------------------------------------+
| Group Religiosity           | cred_grp_relig | numeric/binomial | cred\_    | The mean (proportion) of crt_01: crt_07    |
+-----------------------------+----------------+------------------+-----------+--------------------------------------------+
| Cognitive Style             | crt_type       | categorical      | crt_01:   | ???                                        |
|                             |                |                  |           |                                            |
| (type)                      |                |                  | crt_07    | *Correct*                                  |
|                             |                |                  |           |                                            |
|                             |                |                  |           | *Intuitive*                                |
|                             |                |                  |           |                                            |
|                             |                |                  |           | *Other*                                    |
+-----------------------------+----------------+------------------+-----------+--------------------------------------------+
| Non-Verbal Reasoning        | nverb_score    | numeric          |           |                                            |
+-----------------------------+----------------+------------------+-----------+--------------------------------------------+
| Moralisation of Rationality | mor_score      | numeric          | mor_01:   | $$ \frac{1}{13} \sum_{i=01}^{13} at_{i} $$ |
|                             |                |                  |           |                                            |
|                             |                |                  | mor_09    | The mean of at_01: at_13                   |
+-----------------------------+----------------+------------------+-----------+--------------------------------------------+
| Importance of Rationality   | rat_score      | numeric          | imp_01:   | The mean of imp_01 : imp_06                |
|                             |                |                  |           |                                            |
|                             |                |                  | imp_06    |                                            |
+-----------------------------+----------------+------------------+-----------+--------------------------------------------+
