---
title: "Variables"
format: docx
---

## Measures of Belief

### Belief in God

+-----------------------------+----------------+----------------+------------------+-----------------------------------------------+
| Variable Name               | Variable Label | Variable Type  | Source           | Definition                                    |
|                             |                |                |                  |                                               |
|                             |                |                | (section)        |                                               |
+=============================+================+================+==================+===============================================+
| Belief in God (categorical) | big_01         | categorical    | issp_01          | issp_01 default                               |
|                             |                |                |                  |                                               |
|                             |                |                | (ISSP)           |                                               |
+-----------------------------+----------------+----------------+------------------+-----------------------------------------------+
| Belief in God (binary)      | big_02         | binary (dummy) | issp_01          | dummy variable for responses 1 & 2 in issp_01 |
|                             |                |                |                  |                                               |
|                             |                |                | (ISSP)           |                                               |
+-----------------------------+----------------+----------------+------------------+-----------------------------------------------+
| Belief in God (continuous)  | big_03         | continuous/    | belief_01        | belief_01 default                             |
|                             |                |                |                  |                                               |
|                             |                | ordinal        | (General Belief) |                                               |
+-----------------------------+----------------+----------------+------------------+-----------------------------------------------+
| Agnosticism (continuous)    | agn_01         | continuous/    | agn_01           | agn_01 default                                |
|                             |                |                |                  |                                               |
|                             |                | ordinal        | (General Belief) |                                               |
+-----------------------------+----------------+----------------+------------------+-----------------------------------------------+
| Agnosticism (binary)        | agn_02         | binary         | issp_02          | dummy variable for response 5 in issp_02      |
|                             |                |                |                  |                                               |
|                             |                |                | (ISSP)           |                                               |
+-----------------------------+----------------+----------------+------------------+-----------------------------------------------+

### Atheism

+--------------------+----------------+----------------+----------------------+------------------------------------------+
| Variable Name      | Variable Label | Variable Type  | Source               | Definition                               |
|                    |                |                |                      |                                          |
|                    |                |                | (section)            |                                          |
+====================+================+================+======================+==========================================+
| Atheist Membership | ath_01         | binary         | am_01                | am_01 default                            |
|                    |                |                |                      |                                          |
|                    |                |                | (Atheist Membership) |                                          |
+--------------------+----------------+----------------+----------------------+------------------------------------------+
| Atheist Identity   | ath_02         | binary (dummy) | issp_02              | dummy variable from option 4 for issp_02 |
+--------------------+----------------+----------------+----------------------+------------------------------------------+

### Religiosity

+--------------------------+----------------+---------------+----------------------+----------------+
| Variable Name            | Variable Label | Variable Type | Source               | Definition     |
|                          |                |               |                      |                |
|                          |                |               | (section)            |                |
+==========================+================+===============+======================+================+
| Religious Identification | r_01           | binary        | rid_01               | rid_01 default |
|                          |                |               |                      |                |
|                          |                |               | (Religious Identity) |                |
+--------------------------+----------------+---------------+----------------------+----------------+
| Religious Attendence     | r_02           | continuous/   | rp_01                | rp_01 default  |
|                          |                |               |                      |                |
|                          |                | ordinal       | (Religious Practice) |                |
+--------------------------+----------------+---------------+----------------------+----------------+
| Prayer                   | r_03           | continuous/   | rp_02                | rp_02 default  |
|                          |                |               |                      |                |
|                          |                | ordinal       | (Religious Practice) |                |
+--------------------------+----------------+---------------+----------------------+----------------+
| Religious Objects        | r_04           | continuous/   | rp_03                | rp_03 default  |
|                          |                |               |                      |                |
|                          |                | ordinal       | (Religious Practice) |                |
+--------------------------+----------------+---------------+----------------------+----------------+
| Anti-religiosity         | r_05           | continuous/   | ar_01                | ar_01 default  |
|                          |                |               |                      |                |
|                          |                | ordinal       | (General Belief)     |                |
+--------------------------+----------------+---------------+----------------------+----------------+

### Meta Belief

+------------------------------+----------------+---------------+------------------+-------------------+
| Variable Name                | Variable Label | Variable Type | Source           | Definition        |
|                              |                |               |                  |                   |
|                              |                |               | (section)        |                   |
+==============================+================+===============+==================+===================+
| Possibility of Knowing (God) | mb_01          | continuous/   | belief_02        | belief_02 default |
|                              |                |               |                  |                   |
|                              |                | ordinal       | (General Belief) |                   |
+------------------------------+----------------+---------------+------------------+-------------------+
| Confidence in Belief         | mb_02          | continuous/   | conf_01          | conf_01 default   |
|                              |                |               |                  |                   |
|                              |                | ordinal       | (General Belief) |                   |
+------------------------------+----------------+---------------+------------------+-------------------+
| Apatheism (God)              | mb_03          | continuous/   | apth_01          | apth_01 default   |
|                              |                |               |                  |                   |
|                              |                | ordinal       |                  |                   |
+------------------------------+----------------+---------------+------------------+-------------------+
| Apatheism (life purpose)     | mb_04          | continuous/   | apth_02          | apth_02 default   |
|                              |                |               |                  |                   |
|                              |                | ordinal       |                  |                   |
+------------------------------+----------------+---------------+------------------+-------------------+
| Possibility of Truth         | mb_05          | continuous/   | mean_01          | mean_01 default   |
|                              |                |               |                  |                   |
|                              |                | ordinal       |                  |                   |
+------------------------------+----------------+---------------+------------------+-------------------+
| Naturalism                   |                |               |                  |                   |
+------------------------------+----------------+---------------+------------------+-------------------+

### Supernatural Belief

##### *Afterlife Belief*

+----------------------+----------------+---------------+-----------------------+----------------+
| Variable Name        | Variable Label | Variable Type | Source                | Definition     |
|                      |                |               |                       |                |
|                      |                |               | (section)             |                |
+======================+================+===============+=======================+================+
| Afterlife Existence  | al_01          | continuous/   | snb_01                | snb_01 default |
|                      |                |               |                       |                |
|                      |                | ordinal       | (Supernatural Belief) |                |
+----------------------+----------------+---------------+-----------------------+----------------+
| Afterlife Punishment | al_02          | continuous/   | snb_13                | snb_13 default |
|                      |                |               |                       |                |
|                      |                | ordinal       | (Supernatural Belief) |                |
+----------------------+----------------+---------------+-----------------------+----------------+
| Afterlife            | al_03          | continuous/   | snb_14                | snb_14 default |
|                      |                |               |                       |                |
| Reward               |                | ordinal       | (Supernatural Belief) |                |
+----------------------+----------------+---------------+-----------------------+----------------+

##### *Reincarnation*

+---------------+------------+-------------+-----------------------+----------------+
| Reincarnation | rc_01      | continuous/ | snb_02                | snb_02 default |
|               |            |             |                       |                |
|               |            | ordinal     | (Supernatural Belief) |                |
+---------------+------------+-------------+-----------------------+----------------+

##### *Astrology*

+------------+------------+-------------+-----------------------+----------------+
| Astrology  | ast_01     | continuous/ | snb_03                | snb_03 default |
|            |            |             |                       |                |
|            |            | ordinal     | (Supernatural Belief) |                |
+------------+------------+-------------+-----------------------+----------------+

##### *Mystical Powers*

+------------------+------------+-------------+-----------------------+----------------+
| Mystical People  | mp_01      | continuous/ | snb_04                | snb_04 default |
|                  |            |             |                       |                |
|                  |            | ordinal     | (Supernatural Belief) |                |
+------------------+------------+-------------+-----------------------+----------------+
| Mystical Objects | mp_02      | continuous/ | snb_05                | snb_05 default |
|                  |            |             |                       |                |
|                  |            | ordinal     | (Supernatural Belief) |                |
+------------------+------------+-------------+-----------------------+----------------+

##### *Underlying Forces*

+--------------------------------+-----------+-------------+-----------------------+----------------+
| Good and Evil                  | uf_01     | continuous/ | snb_06                | snb_06 default |
|                                |           |             |                       |                |
|                                |           | ordinal     | (Supernatural Belief) |                |
+--------------------------------+-----------+-------------+-----------------------+----------------+
| Universal spirit or life force | uf_02     | continuous/ | snb_07                | snb_07 default |
|                                |           |             |                       |                |
|                                |           | ordinal     | (Supernatural Belief) |                |
+--------------------------------+-----------+-------------+-----------------------+----------------+
| Karma                          | uf_03     | continuous/ | snb_08                | snb_08 default |
|                                |           |             |                       |                |
|                                |           | ordinal     | (Supernatural Belief) |                |
+--------------------------------+-----------+-------------+-----------------------+----------------+
| Fate                           | uf_04     | continuous/ | snb_09                | snb_09 default |
|                                |           |             |                       |                |
|                                |           | ordinal     | (Supernatural Belief) |                |
+--------------------------------+-----------+-------------+-----------------------+----------------+

##### *Supernatural Beings*

+-----------------------------+------------+-------------+-----------------------+----------------+
| Supernatural Beings         | sb_01      | continuous/ | snb_10                | snb_10 default |
|                             |            |             |                       |                |
|                             |            | ordinal     | (Supernatural Belief) |                |
+-----------------------------+------------+-------------+-----------------------+----------------+
| Good Supernatural Beings    | sb_02      | continuous/ | snb_11                | snb_11 default |
|                             |            |             |                       |                |
|                             |            | ordinal     | (Supernatural Belief) |                |
+-----------------------------+------------+-------------+-----------------------+----------------+
| Harmful Supernatural Beings | sb_03      | continuous/ | snb_12                | snb_12 default |
|                             |            |             |                       |                |
|                             |            | ordinal     | (Supernatural Belief) |                |
+-----------------------------+------------+-------------+-----------------------+----------------+

##### *Evil Eye*

+------------+------------+-------------+-----------------------+----------------+
| Evil Eye   | ee_01      | continuous/ | snb_15                | snb_15 default |
|            |            |             |                       |                |
|            |            | ordinal     | (Supernatural Belief) |                |
+------------+------------+-------------+-----------------------+----------------+

##### *Spiritual Force*

+-----------------+------------+-------------+-----------------------+----------------+
| Spiritual Force | sfp_01     | continuous/ | snb_16                | snb_16 default |
|                 |            |             |                       |                |
| (personal)      |            | ordinal     | (Supernatural Belief) |                |
+-----------------+------------+-------------+-----------------------+----------------+

##### *Lucky Objects*

+--------------+------------+-------------+-----------------------+----------------+
| Lucky Object | lo_01      | continuous/ | snb_17                | snb_17 default |
|              |            |             |                       |                |
|              |            | ordinal     | (Supernatural Belief) |                |
+--------------+------------+-------------+-----------------------+----------------+
