|                  |
|------------------|
| tle: "Variables" |
| rmat: docx       |

All definitions assume reverse scoring has already been done.

## Morals and Values

+------------------------------+--------------------+---------------+------------------------------+-----------------------------+
| Variable Name                | Variable Label     | Variable Type | Source                       | Definition                  |
+==============================+====================+===============+==============================+=============================+
| Individualism & Collectivism | indiv_collectivism | numeric       | Individualism & Collectivism | The mean of ic_01 : ic_15   |
+------------------------------+--------------------+---------------+------------------------------+-----------------------------+
| Rebelliousness (complete)    | rebel_all          | numeric       | Rebelliousness               | The mean of rb_01 : rb_09   |
+------------------------------+--------------------+---------------+------------------------------+-----------------------------+
| Rebelliousness (trolling)    | rebel_troll        | numeric       | Rebelliousness               | The mean of rb_01 : rb_04   |
+------------------------------+--------------------+---------------+------------------------------+-----------------------------+
| Rebelliousness               | rebel_act          | numeric       | Rebelliousness               | The mean of rb_05 : rb_09   |
|                              |                    |               |                              |                             |
| (activism)                   |                    |               |                              |                             |
+------------------------------+--------------------+---------------+------------------------------+-----------------------------+
| Individual Choice Norms      | choice_norms       | numeric       | Rebelliousness               | The mean of icn_01 : icn_06 |
+------------------------------+--------------------+---------------+------------------------------+-----------------------------+

## Cognitive Styles

+-----------------------------+-------------------+------------------+-----------------------------+-----------------------------------------------------------+
| Variable Name               | Variable Label    | Variable Type    | Source                      | Definition                                                |
|                             |                   |                  |                             |                                                           |
|                             |                   |                  | (section)                   |                                                           |
+=============================+===================+==================+=============================+===========================================================+
| Tolerance of Ambiguity      | ambiguity_tol     | numeric          | Tolerance of Ambiguity      | The mean of at_01: at_13                                  |
+-----------------------------+-------------------+------------------+-----------------------------+-----------------------------------------------------------+
| Cognitive Style (correct)   | crt_correct       | numeric/binomial | Thinking Style              | The mean (proportion) of crt_01: crt_07 that are correct  |
+-----------------------------+-------------------+------------------+-----------------------------+-----------------------------------------------------------+
| Cognitive Style             | crt_type          | numeric/binomial | Thinking Style              | The mean (proportion) of crt_01:crt_07 that are intuitive |
|                             |                   |                  |                             |                                                           |
| (intuitive)                 |                   |                  |                             |                                                           |
+-----------------------------+-------------------+------------------+-----------------------------+-----------------------------------------------------------+
| Non-Verbal Reasoning        | nverb_reason      | numeric          | Non-Verbal Reasoning        |                                                           |
+-----------------------------+-------------------+------------------+-----------------------------+-----------------------------------------------------------+
| Moralisation of Rationality | rationality_moral | numeric          | Moralisation of Rationality | $$ \frac{1}{9} \sum_{i=01}^{09} mor_{i} $$                |
|                             |                   |                  |                             |                                                           |
|                             |                   |                  |                             | The mean of mor_01 : mor_09                               |
+-----------------------------+-------------------+------------------+-----------------------------+-----------------------------------------------------------+
| Importance of Rationality   | rationality_imp   | numeric          | Importance of Rationality   | The mean of imp_01 : imp_06                               |
+-----------------------------+-------------------+------------------+-----------------------------+-----------------------------------------------------------+

## Socialisation

+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Variable Name                       | Variable Label          | Variable Type | Source                     | Definition                |
|                                     |                         |               |                            |                           |
|                                     |                         |               | (section)                  |                           |
+=====================================+=========================+===============+============================+===========================+
| CRED                                |                         |               |                            |                           |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRED (Parent)                       |                         |               |                            |                           |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRED (Group)                        |                         |               |                            |                           |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRED (Group Leader)                 |                         |               |                            |                           |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRED (Group Member)                 |                         |               |                            |                           |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRUD Exposure                       | crud_exposure           | numeric       | CRUDs                      | sum of crud_01 : crud_03  |
|                                     |                         |               |                            |                           |
|                                     |                         |               |                            | or                        |
|                                     |                         |               |                            |                           |
|                                     |                         |               |                            | mean of crud_01 : crud_03 |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRUD Parents                        | crud_parent             | ordinal       | CRUDs                      | crud_01                   |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRUD (Group Members)                | crud_grp_memb           | ordinal       | CRUDs                      | crud_02                   |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRUD (Group Leaders)                | crud_grp_leader         | ordinal       | CRUDs                      | crud_03                   |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Non-Theistic Socialisation          | nontheistic_social      | numeric       | Non Theistic Socialisation | mean of nts_01: nts_08    |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Normativity of Religion (all)       | normativity_relig       | numeric       | Normativity of Religion    | mean of norm_01: norm_12  |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Normativity of Religion (Nation)    | normativity_relig_nat   | ordinal       | "                          | mean of norm_01: norm_03  |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Normativity of Religion (Ethnicity) | normativity_relig_ethic | ordinal       | "                          | mean of norm_04: norm_06  |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Normativity of Religion (Peers)     | normativity_relig_peer  | ordinal       | "                          | mean of norm_07: norm_09  |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Normativity of Religion (Group)     | normativity_relig_grp   | ordinal       | "                          | mean of norm_10: norm_12  |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Religious Emphasis                  | relig_emph              | numeric       | Religious Emphasis         | mean of re_01: re_09      |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Parental Circumstances              | pc_01                   | categorical   | Parental Circumstances     | pc_01                     |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Parental Absence Reason             | pc_02                   | categorical   | Parental Circumstances     | pc_02                     |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+

## Motivational

+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Variable Name                       | Variable Label         | Variable Type | Source               | Definition               |
|                                     |                        |               |                      |                          |
|                                     |                        |               | (section)            |                          |
+=====================================+========================+===============+======================+==========================+
| Social Desirability                 | social_desire          | numeric       | Social Desirability  | mean sd_01: sd_08        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Existential Security (current)      | existential_sec_cur    | numeric       | Existential Security | mean es_01: es_07        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Existential Security (future)       | existential_sec_future | numeric       | Existential Security | mean es_08: es_14        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Existential Security (upbringing)   | existential_sec_kid    | numeric       | Existential Security | mean es_15: es_21        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Social Security                     | social_sec             | numeric       | Existential Security | mean ss_01: ss_03        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Wealth Inequality                   | wealth_ineq            | numeric       | Existential Security | mean wi_01: wi_03        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Social Trust                        | social_trust           | numeric       | Existential Security | mean st_01: st_03        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Need for Structure                  | need_structure         | numeric       | Need for Structure   | mean nfs_01: nfs_12      |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Death Anxiety                       | death_anxiety          | numeric       | Death Anxiety        | mean da_01: da_12        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Social Network Size                 | soc_network_size       | numeric       | Social Network Size  | count elements of sns_01 |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Meaning in Life                     | meaning_life           | numeric       | Need for Meaning     | mean mlq_01: mlq_10      |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Need for Meaning                    | meaning_need           | numeric       | Need for Meaning     | mean nfm_01 : nfm_10     |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Disgust Sensitivity                 | disgust_sens           | numeric       | Disgust Sensitivity  |                          |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Disgust Sensitivity (animal)        | disgust_animal         | numeric       | Disgust Sensitivity  |                          |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Disgust Sensitivity (contamination) | disgust_contamin       | numeric       | Disgust Sensitivity  |                          |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+

## Cognitive Bias

+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Variable Name                       | Variable Label      | Variable Type | Source                      | Definition            |
|                                     |                     |               |                             |                       |
|                                     |                     |               | (section)                   |                       |
+=====================================+=====================+===============+=============================+=======================+
| Anthropomorphism                    | anthropomorphism    | numeric       | Anthropomorphism            | mean anth_01: anth_10 |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Mentalizing                         | menatalizing        | numeric       | Mentalizing                 | mean mnt_01: mnt_22   |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Dualism                             | dualism             | numeric       | Dualism                     | mean dua_01: dua_10   |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Pattern Perception                  | pattern_percep      | numeric       | Pattern Perception          | mean pp_01: pp_10     |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Patern Perception (long)            | pattern_percep_long | ordinal       | Pattern Perception          | pp_11                 |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Promiscuous Telology                | promisc_teleology   | numeric       | Promiscuous Telology        | mean tel_01: tel_14   |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Schizotypy                          | schizotypy          | numeric       | Schizotypy                  | mean sz_01: sz_18     |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Schizotypy (reference)              | schizotypy_ref      | numeric       | Schizotypy                  | mean sz_01: sz_09     |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Schizotypy (perceptual experiences) | schizotypy_percep   | numeric       | Schizotypy                  | mean sz_10: sz_18     |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Vividness of Mental Imagery         | vividness_imagery   | numeric       | Vividness of Mental Imagery | mean vvi_01: vvi_32   |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Dissociative Absorbtion             | absorbtion          | numeric       | Dissociative Absorbtion     | mean dab_01: dab_08   |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
