---
title: "Explaining Atheism: Wave 1"
subtitle: "Variables"
format: pdf
tbl-colwidths: [15, 10, 15, 20, 15, 25]
---

## Morals and Values

+------------------------------+--------------------+---------------+------------------------------+-----------------------------+
| Variable Name                | Variable Label     | Variable Type | Source                       | Definition                  |
+==============================+====================+===============+==============================+=============================+
| Individualism & Collectivism | indiv_collectivism | numeric       | Individualism & Collectivism | The mean of ic_01 : ic_15   |
+------------------------------+--------------------+---------------+------------------------------+-----------------------------+
| Rebelliousness (complete)    | rebel_all          | numeric       | Rebelliousness               | The mean of rb_01 : rb_09   |
+------------------------------+--------------------+---------------+------------------------------+-----------------------------+
| Rebelliousness (trolling)    | rebel_troll        | numeric       | Rebelliousness               | The mean of rb_01 : rb_04   |
+------------------------------+--------------------+---------------+------------------------------+-----------------------------+
| Rebelliousness               | rebel_act          | numeric       | Rebelliousness               | The mean of rb_05 : rb_09   |
|                              |                    |               |                              |                             |
| (activism)                   |                    |               |                              |                             |
+------------------------------+--------------------+---------------+------------------------------+-----------------------------+
| Individual Choice Norms      | choice_norms       | numeric       | Rebelliousness               | The mean of icn_01 : icn_06 |
+------------------------------+--------------------+---------------+------------------------------+-----------------------------+

: {tbl-colwidths="\[20, 25, 15, 20, 20\]"}

## Cognitive Styles

+-----------------------------+-------------------+------------------+-----------------------------+-----------------------------------------------------------+
| Variable Name               | Variable Label    | Variable Type    | Source                      | Definition                                                |
|                             |                   |                  |                             |                                                           |
|                             |                   |                  | (section)                   |                                                           |
+=============================+===================+==================+=============================+===========================================================+
| Tolerance of Ambiguity      | ambiguity_tol     | numeric          | Tolerance of Ambiguity      | The mean of at_01: at_13                                  |
+-----------------------------+-------------------+------------------+-----------------------------+-----------------------------------------------------------+
| Cognitive Style (correct)   | crt_correct       | numeric/binomial | Thinking Style              | The mean (proportion) of crt_01: crt_07 that are correct  |
+-----------------------------+-------------------+------------------+-----------------------------+-----------------------------------------------------------+
| Cognitive Style             | crt_type          | numeric/binomial | Thinking Style              | The mean (proportion) of crt_01:crt_07 that are intuitive |
|                             |                   |                  |                             |                                                           |
| (intuitive)                 |                   |                  |                             |                                                           |
+-----------------------------+-------------------+------------------+-----------------------------+-----------------------------------------------------------+
| Non-Verbal Reasoning        | nverb_reason      | numeric          | Non-Verbal Reasoning        |                                                           |
+-----------------------------+-------------------+------------------+-----------------------------+-----------------------------------------------------------+
| Moralisation of Rationality | rationality_moral | numeric          | Moralisation of Rationality | The mean of mor_01 : mor_09                               |
+-----------------------------+-------------------+------------------+-----------------------------+-----------------------------------------------------------+
| Importance of Rationality   | rationality_imp   | numeric          | Importance of Rationality   | The mean of imp_01 : imp_06                               |
+-----------------------------+-------------------+------------------+-----------------------------+-----------------------------------------------------------+

: {tbl-colwidths="\[20, 25, 15, 20, 20\]"}

\newpage

## Socialisation

+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Variable Name                       | Variable Label          | Variable Type | Source                     | Definition                |
|                                     |                         |               |                            |                           |
|                                     |                         |               | (section)                  |                           |
+=====================================+=========================+===============+============================+===========================+
| CRED                                |                         |               |                            |                           |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRED (Parent)                       |                         |               |                            |                           |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRED (Group)                        |                         |               |                            |                           |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRED (Group Leader)                 |                         |               |                            |                           |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRED (Group Member)                 |                         |               |                            |                           |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRUD Exposure                       | crud_exposure           | numeric       | CRUDs                      | sum of crud_01 : crud_03  |
|                                     |                         |               |                            |                           |
|                                     |                         |               |                            | or                        |
|                                     |                         |               |                            |                           |
|                                     |                         |               |                            | mean of crud_01 : crud_03 |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRUD Parents                        | crud_parent             | ordinal       | CRUDs                      | crud_01                   |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRUD (Group Members)                | crud_grp_memb           | ordinal       | CRUDs                      | crud_02                   |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| CRUD (Group Leaders)                | crud_grp_leader         | ordinal       | CRUDs                      | crud_03                   |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Non-Theistic Socialisation          | nontheistic_social      | numeric       | Non Theistic Socialisation | mean of nts_01: nts_08    |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Normativity of Religion (all)       | normativity_relig       | numeric       | Normativity of Religion    | mean of norm_01: norm_12  |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Normativity of Religion (Nation)    | normativity_relig_nat   | ordinal       | "                          | mean of norm_01: norm_03  |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Normativity of Religion (Ethnicity) | normativity_relig_ethic | ordinal       | "                          | mean of norm_04: norm_06  |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Normativity of Religion (Peers)     | normativity_relig_peer  | ordinal       | "                          | mean of norm_07: norm_09  |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Normativity of Religion (Group)     | normativity_relig_grp   | ordinal       | "                          | mean of norm_10: norm_12  |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Religious Emphasis                  | relig_emph              | numeric       | Religious Emphasis         | mean of re_01: re_09      |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Parental Circumstances              | pc_01                   | categorical   | Parental Circumstances     | pc_01                     |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+
| Parental Absence Reason             | pc_02                   | categorical   | Parental Circumstances     | pc_02                     |
+-------------------------------------+-------------------------+---------------+----------------------------+---------------------------+

: {tbl-colwidths="\[20, 25, 15, 20, 20\]"}

\newpage

## Motivational

+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Variable Name                       | Variable Label         | Variable Type | Source               | Definition               |
|                                     |                        |               |                      |                          |
|                                     |                        |               | (section)            |                          |
+=====================================+========================+===============+======================+==========================+
| Social Desirability                 | social_desire          | numeric       | Social Desirability  | mean sd_01: sd_08        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Existential Security (current)      | existential_sec_cur    | numeric       | Existential Security | mean es_01: es_07        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Existential Security (future)       | existential_sec_future | numeric       | Existential Security | mean es_08: es_14        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Existential Security (upbringing)   | existential_sec_kid    | numeric       | Existential Security | mean es_15: es_21        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Social Security                     | social_sec             | numeric       | Existential Security | mean ss_01: ss_03        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Wealth Inequality                   | wealth_ineq            | numeric       | Existential Security | mean wi_01: wi_03        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Social Trust                        | social_trust           | numeric       | Existential Security | mean st_01: st_03        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Need for Structure                  | need_structure         | numeric       | Need for Structure   | mean nfs_01: nfs_12      |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Death Anxiety                       | death_anxiety          | numeric       | Death Anxiety        | mean da_01: da_12        |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Social Network Size                 | soc_network_size       | numeric       | Social Network Size  | count elements of sns_01 |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Meaning in Life                     | meaning_life           | numeric       | Need for Meaning     | mean mlq_01: mlq_10      |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Need for Meaning                    | meaning_need           | numeric       | Need for Meaning     | mean nfm_01 : nfm_10     |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Disgust Sensitivity                 | disgust_sens           | numeric       | Disgust Sensitivity  |                          |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Disgust Sensitivity (animal)        | disgust_animal         | numeric       | Disgust Sensitivity  |                          |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+
| Disgust Sensitivity (contamination) | disgust_contamin       | numeric       | Disgust Sensitivity  |                          |
+-------------------------------------+------------------------+---------------+----------------------+--------------------------+

: {tbl-colwidths="\[20, 25, 15, 20, 20\]"}

\newpage

## Cognitive Bias

+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Variable Name                       | Variable Label      | Variable Type | Source                      | Definition            |
|                                     |                     |               |                             |                       |
|                                     |                     |               | (section)                   |                       |
+=====================================+=====================+===============+=============================+=======================+
| Anthropomorph                       | anthropomorph       | numeric       | Anthropomorph               | mean anth_01: anth_10 |
|                                     |                     |               |                             |                       |
| -ism                                | -ism                |               | -ism                        |                       |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Mentalizing                         | menatalizing        | numeric       | Mentalizing                 | mean mnt_01: mnt_22   |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Dualism                             | dualism             | numeric       | Dualism                     | mean dua_01: dua_10   |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Pattern Perception                  | pattern_percep      | numeric       | Pattern Perception          | mean pp_01: pp_10     |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Patern Perception (long)            | pattern_percep_long | ordinal       | Pattern Perception          | pp_11                 |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Promiscuous Telology                | promisc_teleology   | numeric       | Promiscuous Telology        | mean tel_01: tel_14   |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Schizotypy                          | schizotypy          | numeric       | Schizotypy                  | mean sz_01: sz_18     |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Schizotypy (reference)              | schizotypy_ref      | numeric       | Schizotypy                  | mean sz_01: sz_09     |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Schizotypy (perceptual experiences) | schizotypy_percep   | numeric       | Schizotypy                  | mean sz_10: sz_18     |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Vividness of Mental Imagery         | vividness_imagery   | numeric       | Vividness of Mental Imagery | mean vvi_01: vvi_32   |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+
| Dissociative Absorbtion             | absorbtion          | numeric       | Dissociative Absorbtion     | mean dab_01: dab_08   |
+-------------------------------------+---------------------+---------------+-----------------------------+-----------------------+

: {tbl-colwidths="\[20, 25, 15, 20, 20\]"}

\newpage

## Measures of Belief

All of our measures of belief that use an agreement likert scale have the following options:

+-------------------+---------------------+-------------------+----------------------------+----------------+------------------+----------------+
| **1**             | **2**               | **3**             | **4**                      | **5**          | **6**            | **7**          |
+-------------------+---------------------+-------------------+----------------------------+----------------+------------------+----------------+
| strongly disagree | moderately disagree | slightly disagree | neither agree nor disagree | slightly agree | moderately agree | strongly agree |
+-------------------+---------------------+-------------------+----------------------------+----------------+------------------+----------------+

### Belief in God

+-----------------------------+----------------+---------------------+----------------------------------------------------------------+-------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| Variable Name               | Variable Label | Variable Type       | Description                                                    | Definition                                                  | Response Options                                                                          |
+=============================+================+=====================+================================================================+=============================================================+===========================================================================================+
| Belief in God (categorical) | big_01         | Categorical         | Categorical Response to belief in god options                  | issp_01 default                                             | 1\. I don't believe in God                                                                |
|                             |                |                     |                                                                |                                                             |                                                                                           |
|                             |                |                     |                                                                |                                                             | 2\. I don't know whether there is a God, and I don't believe there is any way to find out |
|                             |                |                     |                                                                |                                                             |                                                                                           |
|                             |                |                     |                                                                |                                                             | 3\. I don't believe in a personal God, but I do believe in a Higher Power of some kind    |
|                             |                |                     |                                                                |                                                             |                                                                                           |
|                             |                |                     |                                                                |                                                             | 4\. I find myself believing in God some of the time, but not at others                    |
|                             |                |                     |                                                                |                                                             |                                                                                           |
|                             |                |                     |                                                                |                                                             | 5\. While I have doubts, I feel that I do believe in God.                                 |
|                             |                |                     |                                                                |                                                             |                                                                                           |
|                             |                |                     |                                                                |                                                             | 6\. I know God really exists and I have no doubt about it.                                |
|                             |                |                     |                                                                |                                                             |                                                                                           |
|                             |                |                     |                                                                |                                                             | 7\. Don't know                                                                            |
+-----------------------------+----------------+---------------------+----------------------------------------------------------------+-------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| Belief in God (binary)      | big_02         | binary (dummy)      | Categorisation of "believers" and "non-believers" from issp_01 | dummy variable for yes responses to either 5 & 6 in issp_01 | 0,1                                                                                       |
+-----------------------------+----------------+---------------------+----------------------------------------------------------------+-------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| Belief in God (continuous)  | big_03         | continuous/ ordinal | Likert measure of agreement with belief in god statement.      | belief_01                                                   | 0,1                                                                                       |
+-----------------------------+----------------+---------------------+----------------------------------------------------------------+-------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| Agnosticism (continuous)    | agn_01         | continuous/ ordinal | Likert scale measure of agreement with agnosticism statement.  | agn_01                                                      | 1 -7                                                                                      |
+-----------------------------+----------------+---------------------+----------------------------------------------------------------+-------------------------------------------------------------+-------------------------------------------------------------------------------------------+
| Agnostic Identity (binary)  | agn_02         | binary              | Categorisation of "agnostics" from issp_01                     | dummy/index variable for response 5 in issp_02              | 0,1                                                                                       |
+-----------------------------+----------------+---------------------+----------------------------------------------------------------+-------------------------------------------------------------+-------------------------------------------------------------------------------------------+

### Atheism

+--------------------+----------------+---------------+--------------------------------------------+------------------------------------------+------------------+
| Variable Name      | Variable Label | Variable Type | Description                                | Definition                               | Response Options |
+====================+================+===============+============================================+==========================================+==================+
| Atheist Membership | ath_01         | binary        | Yes/no to membership of an atheist org.    | am_01 default                            | 0,1              |
+--------------------+----------------+---------------+--------------------------------------------+------------------------------------------+------------------+
| Atheist Identity   | ath_02         | binary        | Categorisation of "athetists" from issp_01 | dummy variable from option 4 for issp_02 | 0,1              |
+--------------------+----------------+---------------+--------------------------------------------+------------------------------------------+------------------+

### Religiosity

+--------------------------+----------------+---------------------+------------------------------------------------+----------------+------------------------------------------------------+
| Variable Name            | Variable Label | Variable Type       | Description                                    | Definition     | Response Options                                     |
+==========================+================+=====================+================================================+================+======================================================+
| Religious Identification | r_01           | binary              | Yes/no belong to a religion                    | rid_01 default | 0,1                                                  |
+--------------------------+----------------+---------------------+------------------------------------------------+----------------+------------------------------------------------------+
| Religious Identity       | r_02           | categorical         | Which religion category                        | rid_02 default | 1\. Protestant                                       |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 2\. Catholic                                         |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 3\. Orthodox (e.g. Greek Orthodox, Russian Orthodox) |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 4\. Sunni                                            |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 5\. Shiite                                           |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 6\. Buddhist                                         |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 7\. Confucian                                        |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 8\. Daoist                                           |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 9\. Hindu                                            |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 10\. Jewish                                          |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 11\. Shinto                                          |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 12\. Other (please specify)                          |
+--------------------------+----------------+---------------------+------------------------------------------------+----------------+------------------------------------------------------+
| Religious Attendance     | r_03           | continuous/ ordinal | Frequency of religious attendence likert scale | rp_01 default  | 1\. More than once a week                            |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 2\. Once a week                                      |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 3\. Once a month                                     |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 4\. Only on special holy days                        |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 5\. Once a year                                      |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 6\. Less often                                       |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 7\. Never, practically never                         |
+--------------------------+----------------+---------------------+------------------------------------------------+----------------+------------------------------------------------------+
| Prayer Frequency         | r_04           | continuous/ ordinal | Frequency of prayer likert scale               | rp_02 default  | 1\. Several times a day                              |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 2\. Once a day                                       |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 3\. Several times each week                          |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 4\. Only when attending religious services           |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 5\. Only on special holy days                        |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 6\. Once a year                                      |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 7\. Less often                                       |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 8\. Never, practically never                         |
+--------------------------+----------------+---------------------+------------------------------------------------+----------------+------------------------------------------------------+
| Religious Objects        | r_05           | categorical         | Presence of religious objects                  | rp_03 default  | 1\. Yes, for religious reasons                       |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 2\. Yes, for non-religious reasons                   |
|                          |                |                     |                                                |                |                                                      |
|                          |                |                     |                                                |                | 3\. No                                               |
+--------------------------+----------------+---------------------+------------------------------------------------+----------------+------------------------------------------------------+
| Anti-religiosity         | r_06           | continuous/ ordinal | Agreement with anti-religiosity statement      | ar_01 default  | 1-7                                                  |
+--------------------------+----------------+---------------------+------------------------------------------------+----------------+------------------------------------------------------+

### Meta Belief

+------------------------------+----------------+---------------+--------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+-------+
| Variable Name                | Variable Label | Variable Type | Description                                                                                                        | Definition                                                                                          |       |
+==============================+================+===============+====================================================================================================================+=====================================================================================================+=======+
| Possibility of Knowing (God) | mb_01          | continuous/   | Agreement with:                                                                                                    | belief_02 default                                                                                   | 1-7   |
|                              |                |               |                                                                                                                    |                                                                                                     |       |
|                              |                | ordinal       | "It is not possible to know if God exists"                                                                         |                                                                                                     |       |
+------------------------------+----------------+---------------+--------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+-------+
| Confidence in Belief         | mb_02          | continuous/   | Agreement with:                                                                                                    | conf_01 default                                                                                     | 1-7   |
|                              |                |               |                                                                                                                    |                                                                                                     |       |
|                              |                | ordinal       | "I am confident that my beliefs about God's existence are the right ones"                                          |                                                                                                     |       |
+------------------------------+----------------+---------------+--------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+-------+
| Apatheism (God)              | mb_03          | continuous/   | Agreement with:                                                                                                    | apth_01 default                                                                                     | 1-7   |
|                              |                |               |                                                                                                                    |                                                                                                     |       |
|                              |                | ordinal       | "Whether or not God exists is a question that doesn't interest me much"                                            |                                                                                                     |       |
+------------------------------+----------------+---------------+--------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+-------+
| Apatheism (life purpose)     | mb_04          | continuous/   | Agreement with: "Whether or not there is an ultimate purpose to life is a question that doesn't interest me much." | apth_02 default                                                                                     | 1-7   |
|                              |                |               |                                                                                                                    |                                                                                                     |       |
|                              |                | ordinal       |                                                                                                                    |                                                                                                     |       |
+------------------------------+----------------+---------------+--------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+-------+
| Apatheism (combined)         | mb_05          | continuous/   | Agreement with:                                                                                                    |                                                                                                     | 1-7   |
|                              |                |               |                                                                                                                    |                                                                                                     |       |
|                              |                | ordinal       | "I don't know whether there is a God, and I don't believe there is any way to find out."                           |                                                                                                     |       |
+------------------------------+----------------+---------------+--------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+-------+
| Possibility of Truth         | mb_05          | continuous/   | Agreement with:                                                                                                    | mean_01 default                                                                                     | 1-7   |
|                              |                |               |                                                                                                                    |                                                                                                     |       |
|                              |                | ordinal       | "For most things in the world, we will never be able to discover the real objective truth."                        |                                                                                                     |       |
+------------------------------+----------------+---------------+--------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+-------+
| Naturalism                   | mb_07          | binary        |                                                                                                                    | dummy variable = 0 for cases where any of snb items (except 16, 17) are \> 4 (agreement or neither) | 1-7   |
+------------------------------+----------------+---------------+--------------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------+-------+

### Supernatural Belief

##### *Afterlife Belief*

+----------------------+----------------+---------------+------------------------------------------------+----------------+------------------+
| Variable Name        | Variable Label | Variable Type | Description                                    | Definition     | Response Options |
+======================+================+===============+================================================+================+==================+
| Afterlife Existence  | al_01          | continuous/   | Agreement with:                                | snb_01 default | 1-7              |
|                      |                |               |                                                |                |                  |
|                      |                | ordinal       | "There is some sort of life after death"       |                |                  |
+----------------------+----------------+---------------+------------------------------------------------+----------------+------------------+
| Afterlife Punishment | al_02          | continuous/   | Agreement with:                                | snb_13 default | 1-7              |
|                      |                |               |                                                |                |                  |
|                      |                | ordinal       | "Some people will be punished after they die." |                |                  |
+----------------------+----------------+---------------+------------------------------------------------+----------------+------------------+
| Afterlife            | al_03          | continuous/   | Agreement with:                                | snb_14 default | 1-7              |
|                      |                |               |                                                |                |                  |
| Reward               |                | ordinal       | "Some people will be rewarded after they die"  |                |                  |
+----------------------+----------------+---------------+------------------------------------------------+----------------+------------------+

##### *Reincarnation*

+---------------+-------+-------------+---------------------------------------------------------------------------+----------------+-------+
| Reincarnation | rc_01 | continuous/ | Agreement with:                                                           | snb_02 default | 1-7   |
|               |       |             |                                                                           |                |       |
|               |       | ordinal     | "Sometime after I die, I expect that I'll be born again in another body." |                |       |
+---------------+-------+-------------+---------------------------------------------------------------------------+----------------+-------+

##### *Astrology*

+-----------+--------+-------------+----------------------------------------------------------------+----------------+-------+
| Astrology | ast_01 | continuous/ | Agreement with:                                                | snb_03 default | 1-7   |
|           |        |             |                                                                |                |       |
|           |        | ordinal     | "The positions of the stars and planets affect people's lives" |                |       |
+-----------+--------+-------------+----------------------------------------------------------------+----------------+-------+

##### *Mystical Powers*

+------------------+-------+-------------+------------------------------------------------------------------------------+----------------+-------+
| Mystical People  | mp_01 | continuous/ | Agreement with:                                                              | snb_04 default | 1-7   |
|                  |       |             |                                                                              |                |       |
|                  |       | ordinal     | Some people have mystical powers (e.g. to heal, harm, or bring good luck)    |                |       |
+------------------+-------+-------------+------------------------------------------------------------------------------+----------------+-------+
| Mystical Objects | mp_02 | continuous/ | Agreement with:                                                              | snb_05 default | 1-7   |
|                  |       |             |                                                                              |                |       |
|                  |       | ordinal     | "Some objects have mystical powers (e.g. to heal, harm, or bring good luck)" |                |       |
+------------------+-------+-------------+------------------------------------------------------------------------------+----------------+-------+

##### *Underlying Forces*

+--------------------------------+-------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
| Good and Evil                  | uf_01 | continuous/ | Agreement with:                                                                                                                                            | snb_06 default | 1-7 |
|                                |       |             |                                                                                                                                                            |                |     |
|                                |       | ordinal     | "There are underlying forces of good and evil in this world."                                                                                              |                |     |
+--------------------------------+-------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
| Universal spirit or life force | uf_02 | continuous/ | Agreement with:                                                                                                                                            | snb_07 default | 1-7 |
|                                |       |             |                                                                                                                                                            |                |     |
|                                |       | ordinal     | "There exists a universal spirit or life force."                                                                                                           |                |     |
+--------------------------------+-------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
| Karma                          | uf_03 | continuous/ | Agreement with:                                                                                                                                            | snb_08 default | 1-7 |
|                                |       |             |                                                                                                                                                            |                |     |
|                                |       | ordinal     | "There is a power in the universe that causes good things to happen to people who behave morally and bad things to happen to people who behave immorally." |                |     |
+--------------------------------+-------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+
| Fate                           | uf_04 | continuous/ | Agreement with:                                                                                                                                            | snb_09 default | 1-7 |
|                                |       |             |                                                                                                                                                            |                |     |
|                                |       | ordinal     | "Most significant life events are meant to be and happen for a reason."                                                                                    |                |     |
+--------------------------------+-------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------+-----+

##### *Supernatural Beings*

+------------------------------+--------+---------------------+------------------------------------------------------------------------------+----------------+--------+
| Supernatural Being Existence | sb_01  | continuous/ ordinal | Agreement with:                                                              | snb_10 default | 1-7    |
|                              |        |                     |                                                                              |                |        |
|                              |        |                     | "Supernatural beings of some kind exist"                                     |                |        |
+------------------------------+--------+---------------------+------------------------------------------------------------------------------+----------------+--------+
| Good Supernatural Beings     | sb_02  | continuous/ ordinal | Agreement with:                                                              | snb_11 default | 1-7    |
|                              |        |                     |                                                                              |                |        |
|                              |        |                     | "There exist supernatural beings that are good/kind (e.g. COUNTRY SPECIFIC)" |                |        |
+------------------------------+--------+---------------------+------------------------------------------------------------------------------+----------------+--------+
| Harmful Supernatural Beings  | sb_03  | continuous/ordinal  | Agreement with:                                                              | snb_12 default | 1-7    |
|                              |        |                     |                                                                              |                |        |
|                              |        |                     | "There exist supernatural beings that are harmful. (e.g COUNTRY SPECIFIC)"   |                |        |
+------------------------------+--------+---------------------+------------------------------------------------------------------------------+----------------+--------+

##### *Evil Eye*

+----------+-------+---------------------+-----------------------------------------------------------------------+----------------+-------+
| Evil Eye | ee_01 | continuous /ordinal | Agreement with:                                                       | snb_15 default | 1-7   |
|          |       |                     |                                                                       |                |       |
|          |       |                     | "Making other people envious of you can cause illness or misfortune." |                |       |
+----------+-------+---------------------+-----------------------------------------------------------------------+----------------+-------+

##### *Spiritual Experience*

+----------------------+--------+--------------------+---------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------+
| Spiritual Experience | sfp_01 | continuous/ordinal | Category response to:                                                           | snb_16 default | 1\. Yes, I've had an experience like this.                                              |
|                      |        |                    |                                                                                 |                |                                                                                         |
| (personal)           |        |                    | "Have you ever felt as though you were connected to a powerful spiritual force? |                | 2\. I've had an experience like this, but I didn't associate it with a spiritual force. |
|                      |        |                    |                                                                                 |                |                                                                                         |
|                      |        |                    |                                                                                 |                | 3\. No, I've never had an experience like this.                                         |
+----------------------+--------+--------------------+---------------------------------------------------------------------------------+----------------+-----------------------------------------------------------------------------------------+

##### *Lucky Objects*

+--------------+-------+--------+----------------------------------------------------+----------------+-------+
| Lucky Object | lo_01 | binary | Yes/No to:                                         | snb_17 default | 1-7   |
|              |       |        |                                                    |                |       |
|              |       |        | "Do you carry any objects for luck or protection?" |                |       |
+--------------+-------+--------+----------------------------------------------------+----------------+-------+
